version: "3"

services:
  db:
    env_file:
      - .sharp.db.env
    image: mariadb:10.6.4
    container_name: db.sharp
    networks:
      - sharp
    volumes:
      - db.sharp:/var/lib/mysql
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100m"
    command: --character-set-client-handshake=FALSE
  inventory:
    volumes:
      - ./inventory.application.yaml:./application.yaml
    image: lunacircle4/sharp:1.0.2
    container_name: inventory.sharp
    networks:
      - sharp
    depends_on:
      - db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100m"
  web:
    image: nginx
    container_name: web.sharp
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/freshtuna.site/fullchain.pem:/etc/letsencrypt/live/freshtuna.site/fullchain.pem
      - /etc/letsencrypt/live/freshtuna.site/privkey.pem:/etc/letsencrypt/live/freshtuna.site/privkey.pem
    networks:
      - sharp
    ports:
      - "443:443"
      - "80:80"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100m"

networks:
  sharp:

volumes:
  db.sharp:
